return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    delay = 0,
    sort = { "alphanum" },
    icons = {
      mappings = false,
      keys = {},
    },
    spec = {
      { "<leader>a", group = "ai" },
      { "<leader>b", group = "buffer" },
      { "<leader>c", group = "code" },
      { "<leader>d", group = "diagnostics" },
      { "<leader>f", group = "find" },
      { "<leader>g", group = "git" },
      { "<leader>l", group = "lsp" },
      { "<leader>m", group = "markdown" },
      { "<leader>n", group = "notify" },
      { "<leader>p", group = "paste" },
      { "<leader>q", group = "quit" },
      { "<leader>s", group = "search" },
      { "<leader>t", group = "triforce" },
      { "<leader>u", group = "utils" },
      { "<leader>w", group = "window" },
      { "<leader>x", group = "trouble" },
      { "<leader><Tab>", group = "tabs" },
    },
  },
}
